### ISSUE TITLE
Command failed: convert: no decode delegate for this image format `JPG'

### ISSUE THREAD

**Issue by HarborZeng** [vkuznecovas/hexo-img-optimization#2]
OS: ubuntu18.04
built and installed imagemagick from source.
run test summary like this 
```bash
============================================================================
Testsuite summary for ImageMagick 7.0.8
============================================================================
# TOTAL: 86
# PASS:  84
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
```
when running  ```hexo img```
```bash
...some more file...
INFO  [IMG] Completed processing: public/p/use-python-to-write-a-crawler-crawl-jingdong-commodity-reviews-analyze-emotional-sentiment-and-draw-word-cloud/默认好评.png
INFO  [IMG] Completed processing: public/p/observation-of-a-practical-network-the-software-engineering-course-northwest-university/browser.png
INFO  [IMG] Completed processing: public/p/observation-of-a-practical-network-the-software-engineering-course-northwest-university/cover.jpg
...some more files...
```
suddenly got a error like this
```bash
ERROR [IMG] Proccessing failed for public/p/northwest-university-software-engineering-uml-unified-modeling-language-final-exam-review-materials/cover-uml.jpg
/home/harntu/hexo-tellyouwhat/node_modules/hexo-img-optimization/index.js:52
        throw err
        ^

Error: Command failed: convert: no decode delegate for this image format `JPG' @ error/constitute.c/ReadImage/556.
convert: no images defined `public/p/northwest-university-software-engineering-uml-unified-modeling-language-final-exam-review-materials/cover-uml.jpg' @ error/convert.c/ConvertImageCommand/3300.

    at ChildProcess.<anonymous> (/home/harntu/hexo-tellyouwhat/node_modules/_imagemagick@0.1.3@imagemagick/imagemagick.js:88:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```
what should I do? @vkuznecovas

**Comment by HarborZeng** [comment]
problem solved, anyone who wonder the same answer, here are some tip: <https://stackoverflow.com/questions/9586048/imagemagick-no-decode-delegate>
